# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsm < Formula
  desc "AWS SSM Utility"
  homepage "https://github.com/yasithab/aws-ssm"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/aws-ssm/releases/download/1.0.2/aws-ssm_Darwin_x86_64.tar.gz"
      sha256 "e1c640ea8d0d9ebb76f2efb379080cd801a95e1eb039a9f5edd069c9f2544c2a"

      def install
        bin.install "aws-ssm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/aws-ssm/releases/download/1.0.2/aws-ssm_Darwin_arm64.tar.gz"
      sha256 "d6c65740abe514465ef9221afa061222c093018d5dde5d2404ba85a804af2fb4"

      def install
        bin.install "aws-ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yasithab/aws-ssm/releases/download/1.0.2/aws-ssm_Linux_x86_64.tar.gz"
        sha256 "e847ab5fd4297d4cc6dcbf02201dca083d579789b268810e7b4a4d02f7a7d5cf"

        def install
          bin.install "aws-ssm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yasithab/aws-ssm/releases/download/1.0.2/aws-ssm_Linux_arm64.tar.gz"
        sha256 "41b307d14ca58ab22086d262d23c637a388e614bb5bc8ed18c0f823332d2d284"

        def install
          bin.install "aws-ssm"
        end
      end
    end
  end

  test do
    system "#{bin}/aws-ssm --version"
  end
end
